platform :ios, '12.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  pod 'Firebase/Core'

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
